### ISSUE TITLE
The crate rebuilds libcurl and other things everytime a tiny detail in the source is changed

### ISSUE THREAD

**Issue by Dr-42** [Jibble330/image_search#1]

**Comment by commonkestrel** [comment]
It seems like it might be an issue with [`surf`](https://github.com/http-rs/surf). Try changing the dependency to `image_search = { version = "0.4.0", default-features=false, features=["hyper"] }` in Cargo.toml. If this fixes the issue I'll make `hyper` the default client.

**Comment by Dr-42** [comment]
I am using the blocking version. Could you possibly guide me about that?

**Comment by commonkestrel** [comment]
Should be the same idea, just add the blocking feature as well: `image_search = { version = "0.4.0", default-features=false, features=["hyper", "blocking"] }`

**Comment by Dr-42** [comment]
This solves the issue. Thanks for the help.
