### ISSUE TITLE
The dependencies used seems to use a very old version of tokio, preventing to use with a more recent one

### ISSUE THREAD

**Issue by iXo** [Jibble330/image_search#2]
Hi,

I am new to rust, but I tried to use your crates to download some pictures from google images (is there a way to pick a random one ?).

But my problem is that in my dependencies I am already have tokio as version 1.26.0.

When starting a simple image search (async) like in your sample, I have this error :

`thread 'main' panicked at 'there is no timer running, must be called from the context of a Tokio 0.2.x runtime', /home/ixo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/time/driver/handle.rs:24:32`

If I use cargo tree, I see that :

 
>├── image_search v0.4.1
>│   ├── async-std v1.12.0
>│   │   ├── async-channel v1.8.0
>│   │   │   ├── concurrent-queue v2.1.0
>│   │   │   │   └── crossbeam-utils v0.8.15 (*)
>│   │   │   ├── event-listener v2.5.3
>│   │   │   └── futures-core v0.3.26
>│   │   ├── async-global-executor v2.3.1
>│   │   │   ├── async-channel v1.8.0 (*)
>│   │   │   ├── async-executor v1.5.0
>│   │   │   │   ├── async-lock v2.7.0
>│   │   │   │   │   └── event-listener v2.5.3
>│   │   │   │   ├── async-task v4.3.0
>│   │   │   │   ├── concurrent-queue v2.1.0 (*)
>│   │   │   │   .... snip ....
>│   │   │   ├── once_cell v1.17.1
>│   │   │   └── tokio v0.2.25
>...

What can we do ?

**Comment by commonkestrel** [comment]
Seems like [`http-client`](https://crates.io/crates/http-client) uses tokio 0.2, I believe there's something in [`async-std`](https://crates.io/crates/async-std) that can handle runtime errors like this. I'll play around with this and see what I can do.

**Comment by iXo** [comment]
It seems that both async-std and async-global-executor allow to choose the flavor of tokio, so maybe by using features in image_search we could do the same ?

`async-global-executor = { version = "2.3.1", features = ["tokio"] }`
`async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }`
